name: Credentials 🔐
about: For secure management and tracking of access info
title: ''
labels: ''
projects: ["Space-2k25/6"]
assignees: ''
type: "Credentials 🔐"
body:
  - type: markdown
    attributes:
      value: |
        ### Objective

        - 

        ### Acceptance Criteria

        - [ ] 

        ### Context

        -
