name: Task 📀
about: For creating tasks issues
title: ''
labels: ''
projects: ["Space-2k25/3"]
assignees: ''
type: "Task 📀"
body:
  - type: markdown
    attributes:
      value: |
        ### Objective

        - 

        ### Acceptance Criteria

        - [ ] 

        ### Context

        -
