name: Legal ⚖️
about: For security, IP, or compliance-related tasks
title: ''
labels: []
assignees: []
type: "Legal ⚖️"
body:
  - type: markdown
    attributes:
      value: |
        ### Objective

        - 

        ### Acceptance Criteria

        - [ ] 

        ### Context

        -
